"""NetCDF infrastructure for extracting un-interpreted GloFAS forecast data."""

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from math import isfinite
from pathlib import Path

from netCDF4 import Dataset, Variable, num2date

from backend.app.forecast.exceptions import ForecastParsingError


_DISCHARGE_VARIABLE_NAMES = (
    "dis24",
    "river_discharge_in_the_last_24_hours",
)
_LATITUDE_VARIABLE_NAMES = ("latitude", "lat")
_LONGITUDE_VARIABLE_NAMES = ("longitude", "lon")
_REFERENCE_TIME_VARIABLE_NAMES = ("time", "forecast_reference_time")
_STEP_VARIABLE_NAMES = ("step", "forecast_period", "leadtime_hour")
_VALID_TIME_VARIABLE_NAMES = ("valid_time",)


@dataclass(frozen=True, slots=True)
class ParsedForecastSnapshot:
    """Typed, provider-shaped values extracted from one local GloFAS snapshot."""

    snapshot_path: Path
    dataset_name: str
    product_type: str
    hydrological_model: str
    system_version: str
    retrieved_at: datetime
    forecast_reference_time: datetime
    latitudes: tuple[float, ...]
    longitudes: tuple[float, ...]
    valid_times: tuple[datetime, ...]
    lead_time_hours: tuple[int, ...]
    discharge_values: tuple[tuple[tuple[float, ...], ...], ...]


class NetCDFForecastParser:
    """Extract validated GloFAS coordinate, time, and discharge arrays from NetCDF."""

    def parse(self, snapshot_path: Path) -> ParsedForecastSnapshot:
        """Read one local NetCDF snapshot without selecting a grid cell or mapping domain data.

        Args:
            snapshot_path: Existing raw NetCDF snapshot generated by ingestion.

        Returns:
            Immutable raw forecast structures ready for pure domain mapping.

        Raises:
            ForecastParsingError: If the snapshot is missing, invalid, or unsupported.
        """

        if not snapshot_path.is_file() or snapshot_path.suffix.lower() != ".nc":
            raise ForecastParsingError("Forecast snapshot must be an existing .nc file.")

        try:
            with Dataset(snapshot_path, mode="r") as dataset:
                return self._parse_dataset(snapshot_path, dataset)
        except ForecastParsingError:
            raise
        except Exception as error:
            raise ForecastParsingError("Unable to open GloFAS NetCDF snapshot.") from error

    def _parse_dataset(self, snapshot_path: Path, dataset: Dataset) -> ParsedForecastSnapshot:
        """Extract required variables from an already opened NetCDF dataset."""

        latitude = _required_variable(dataset, _LATITUDE_VARIABLE_NAMES, "latitude")
        longitude = _required_variable(dataset, _LONGITUDE_VARIABLE_NAMES, "longitude")
        reference_time = _required_variable(
            dataset,
            _REFERENCE_TIME_VARIABLE_NAMES,
            "forecast reference time",
        )
        step = _required_variable(dataset, _STEP_VARIABLE_NAMES, "forecast lead time")
        discharge = _required_variable(dataset, _DISCHARGE_VARIABLE_NAMES, "river discharge")

        latitudes = _coordinate_values(latitude, "latitude")
        longitudes = _coordinate_values(longitude, "longitude")
        forecast_reference_time = _single_time(reference_time, "forecast reference time")
        lead_time_hours = _lead_time_hours(step)
        valid_time_variable = _optional_variable(dataset, _VALID_TIME_VARIABLE_NAMES)
        valid_times = (
            _valid_times(valid_time_variable, len(lead_time_hours))
            if valid_time_variable is not None
            else tuple(
                forecast_reference_time + timedelta(hours=lead_time)
                for lead_time in lead_time_hours
            )
        )
        discharge_values = _discharge_values(
            discharge,
            latitude.name,
            longitude.name,
            reference_time.name,
            step.name,
            len(lead_time_hours),
            len(latitudes),
            len(longitudes),
        )

        return ParsedForecastSnapshot(
            snapshot_path=snapshot_path,
            dataset_name=_required_attribute(dataset, "dataset_name"),
            product_type=_required_attribute(dataset, "product_type"),
            hydrological_model=_required_attribute(dataset, "hydrological_model"),
            system_version=_required_attribute(dataset, "system_version"),
            retrieved_at=datetime.fromtimestamp(snapshot_path.stat().st_mtime, tz=UTC),
            forecast_reference_time=forecast_reference_time,
            latitudes=latitudes,
            longitudes=longitudes,
            valid_times=valid_times,
            lead_time_hours=lead_time_hours,
            discharge_values=discharge_values,
        )


def _required_variable(dataset: Dataset, names: tuple[str, ...], label: str) -> Variable:
    """Return one required NetCDF variable or raise a clear parsing failure."""

    variable = _optional_variable(dataset, names)
    if variable is None:
        raise ForecastParsingError(f"GloFAS snapshot is missing required {label} data.")
    return variable


def _optional_variable(dataset: Dataset, names: tuple[str, ...]) -> Variable | None:
    """Return the first provider-supported variable present in a dataset."""

    return next((dataset.variables[name] for name in names if name in dataset.variables), None)


def _coordinate_values(variable: Variable, label: str) -> tuple[float, ...]:
    """Read a non-empty, finite one-dimensional coordinate array."""

    if variable.ndim != 1:
        raise ForecastParsingError(f"GloFAS {label} coordinates must be one-dimensional.")
    values = tuple(float(value) for value in variable[:])
    if not values or not all(isfinite(value) for value in values):
        raise ForecastParsingError(f"GloFAS {label} coordinates must be finite and non-empty.")
    return values


def _single_time(variable: Variable, label: str) -> datetime:
    """Decode exactly one CF-compliant NetCDF time value as UTC."""

    if variable.size != 1:
        raise ForecastParsingError(f"GloFAS {label} must contain exactly one value.")
    return _decode_time(variable, variable[:].reshape(-1)[0])


def _valid_times(variable: Variable, expected_count: int) -> tuple[datetime, ...]:
    """Decode a valid-time coordinate and validate its lead-time cardinality."""

    values = variable[:]
    if variable.ndim == 0:
        if expected_count != 1:
            raise ForecastParsingError("GloFAS valid_time does not match forecast lead times.")
        return (_decode_time(variable, values.item()),)
    if variable.ndim == 2:
        if variable.shape[0] != 1:
            raise ForecastParsingError("GloFAS valid_time supports one reference time only.")
        values = values[0]
    if variable.ndim not in {1, 2} or len(values) != expected_count:
        raise ForecastParsingError("GloFAS valid_time does not match forecast lead times.")
    return tuple(_decode_time(variable, value) for value in values)


def _decode_time(variable: Variable, value: object) -> datetime:
    """Decode one CF time coordinate and normalize it to a timezone-aware UTC datetime."""

    units = getattr(variable, "units", None)
    if not isinstance(units, str) or not units:
        raise ForecastParsingError("GloFAS time coordinate is missing CF units.")
    decoded = num2date(
        value,
        units=units,
        calendar=getattr(variable, "calendar", "standard"),
        only_use_cftime_datetimes=False,
        only_use_python_datetimes=False,
    )
    return datetime(
        decoded.year,
        decoded.month,
        decoded.day,
        decoded.hour,
        decoded.minute,
        decoded.second,
        tzinfo=UTC,
    )


def _lead_time_hours(variable: Variable) -> tuple[int, ...]:
    """Read finite non-negative lead times in a supported CF duration unit."""

    if variable.ndim != 1:
        raise ForecastParsingError("GloFAS forecast lead times must be one-dimensional.")
    unit = str(getattr(variable, "units", "hours")).lower()
    multiplier = _lead_time_multiplier(unit)
    values = tuple(float(value) for value in variable[:])
    if not values or not all(isfinite(value) and value >= 0 for value in values):
        raise ForecastParsingError("GloFAS forecast lead times must be finite and non-negative.")
    lead_times = tuple(int(value * multiplier) for value in values)
    if any(value * multiplier != int(value * multiplier) for value in values):
        raise ForecastParsingError("GloFAS forecast lead times must resolve to whole hours.")
    return lead_times


def _lead_time_multiplier(unit: str) -> int:
    """Return the multiplier required to express a supported duration unit in hours."""

    if unit.startswith("hour"):
        return 1
    if unit.startswith("day"):
        return 24
    raise ForecastParsingError("GloFAS forecast lead-time units must be hours or days.")


def _discharge_values(
    variable: Variable,
    latitude_name: str,
    longitude_name: str,
    reference_time_name: str,
    step_name: str,
    step_count: int,
    latitude_count: int,
    longitude_count: int,
) -> tuple[tuple[tuple[float, ...], ...], ...]:
    """Extract control-forecast discharge arrays in time, latitude, longitude order."""

    dimensions = tuple(variable.dimensions)
    expected_dimension_suffix = (latitude_name, longitude_name)
    expected_dimension_prefixes = (
        (reference_time_name, step_name),
        (step_name, reference_time_name),
    )
    if dimensions[:2] not in expected_dimension_prefixes or dimensions[2:] != expected_dimension_suffix:
        raise ForecastParsingError(
            "GloFAS river discharge must use forecast reference time, lead time, "
            "latitude, and longitude dimensions."
        )
    if (
        variable.shape[2:] != (latitude_count, longitude_count)
        or variable.shape[dimensions.index(reference_time_name)] != 1
        or variable.shape[dimensions.index(step_name)] != step_count
    ):
        raise ForecastParsingError("GloFAS river discharge dimensions do not match coordinates.")

    values: list[tuple[tuple[float, ...], ...]] = []
    for step_index in range(step_count):
        temporal_indices = (
            (0, step_index)
            if dimensions[0] == reference_time_name
            else (step_index, 0)
        )
        plane = tuple(
            tuple(
                float(value)
                for value in variable[
                    temporal_indices[0],
                    temporal_indices[1],
                    latitude_index,
                    :,
                ]
            )
            for latitude_index in range(latitude_count)
        )
        if not all(isfinite(value) and value >= 0 for row in plane for value in row):
            raise ForecastParsingError("GloFAS river discharge contains invalid values.")
        values.append(plane)
    return tuple(values)


def _required_attribute(dataset: Dataset, name: str) -> str:
    """Return one required, non-blank NetCDF provenance attribute.

    Args:
        dataset: Open NetCDF dataset containing GloFAS metadata.
        name: Required global attribute name.

    Returns:
        The stripped metadata value.

    Raises:
        ForecastParsingError: If the required attribute is absent or blank.
    """

    value = getattr(dataset, name, None)
    if not isinstance(value, str) or not value.strip():
        raise ForecastParsingError(f"Missing required metadata attribute: {name}")
    return value.strip()
