"""Composition boundary for existing forecast and GIS production services."""

import asyncio

from backend.app.core.logger import get_logger
from backend.app.gis.analysis_tool import GISAnalysisRequest, GISAnalysisTool
from backend.app.gis.domain.exceptions import GISDomainServiceError
from backend.app.gis.domain.models import GISDomainRequest
from backend.app.gis.domain.protocols import InfrastructureProvider, RiverProvider
from backend.app.gis.evidence import FloodEvidence
from backend.app.gis.river.loader import RiverNetworkLoader
from backend.app.gis.processing.osm import OSMLoader

_LOGGER = get_logger(__name__)


class GISDomainService:
    """Compose existing GIS boundaries into one canonical flood-evidence operation."""

    def __init__(
        self,
        river_loader: RiverProvider,
        osm_loader: InfrastructureProvider,
        gis_analysis_tool: GISAnalysisTool,
    ) -> None:
        """Initialize explicit production dependencies for GIS orchestration."""
        self._river_loader = river_loader
        self._osm_loader = osm_loader
        self._gis_analysis_tool = gis_analysis_tool

    async def execute(self, request: GISDomainRequest) -> FloodEvidence:
        """Load production inputs once and return canonical flood evidence.

        Args:
            request: Prepared immutable forecast, severity, and analysis extent.

        Returns:
            The existing canonical ``FloodEvidence`` generated by GISAnalysisTool.

        Raises:
            GISDomainServiceError: If any composed production boundary fails.
        """
        if not isinstance(request, GISDomainRequest):
            raise GISDomainServiceError(
                "GIS domain execution requires a GISDomainRequest."
            )
        _LOGGER.info("GIS domain execution started")
        try:
            river = await asyncio.to_thread(
                self._river_loader.get_geometry, request.context.bounds
            )
            _LOGGER.info("GIS domain river geometry resolved")
            infrastructure = await asyncio.to_thread(
                self._osm_loader.load, request.context.bounds
            )
            _LOGGER.info("GIS domain infrastructure loaded")
            evidence = await self._gis_analysis_tool.execute(
                GISAnalysisRequest(
                    forecast=request.context.forecast,
                    severity=request.context.severity,
                    river_geometry=river.geometry,
                    river_crs=river.crs,
                    infrastructure_layers=infrastructure,
                )
            )
        except Exception as error:
            _LOGGER.error(
                "GIS domain execution failed: error_type=%s", type(error).__name__
            )
            raise GISDomainServiceError("GIS domain execution failed.") from error
        _LOGGER.info("GIS domain GIS analysis completed")
        _LOGGER.info("GIS domain execution finished")
        return evidence
